#!/usr/bin/env node
'use strict'

const { spawn } = require('child_process');
const program = require('commander');
const pkg = require('../package.json');
const status = require('./status');

program
  .version(pkg.version)
  .description(pkg.description)
  .usage('<command>')

program
  .command('status')
  .description('get current local status')
  .action(() => {
    status.branch()
      .then(data => console.log(data));
  })

program.parse(process.argv);

// if (!program.args.filter(arg => typeof arg === 'object').length) {
//   program.help();
// }
